version: '3'

networks:
    app_network:
        name: auth_network

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx_auth
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - php
            - mysql
        networks:
            - app_network

    mysql:
        image: mysql:5.7
        container_name: mysql_auth
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: auth_db
            MYSQL_USER: havt
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app_network

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 81:80
        environment:
            - PMA_ARBITRARY=1
        networks:
            - app_network

    php:
        build:
            context: .
            dockerfile: docker/php.dockerfile
        image: laravel_php_8
        user: '${UID:-1000}:${GID:-1000}'
        container_name: php_auth
        volumes:
            - ./:/var/www/html
        ports:
            - 9000:9000
        networks:
            - app_network
